name:                  lint

on:
  push:
    branches:
      - master
      - bugfixes
      - development
    paths:
      - '**/*.swift'
  repository_dispatch:
    types:             [lint-command, build-command]

jobs:
  lint:
    runs-on:           ubuntu-latest
    
    steps:
      - uses:          actions/checkout@v1
      - uses:          norio-nomura/action-swiftlint@3.1.0
        with:
          args:        --strict
