name:                   opening

on:
  pull_request:
    types:              [opened]
  issues:
    types:              [opened]

jobs:
  sponsors:
    runs-on:            ubuntu-latest

    steps:
      - uses:           JasonEtco/is-sponsor-label-action@master
        with:
          label:        sponsor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
